#!/usr/bin/env -S deno run -A --lock=tools/deno.lock.json
import { walk } from "jsr:@std/fs/walk";
import * as path from "jsr:@std/path";

const data = await createTypeImports("uix", "./src/");
const regex = /^\/\* \<module\>[*\S\s]*\<\/module\>.*$/gm;
const token = Deno.env.get("GITHUB_TOKEN");

const repository = Deno.args.at(0);
if (!repository)
	throw new Error("Could not get git repository");
if (!token)
	throw new Error("Could not get git token");

/**
 * Replacing the following references (without the _):
 * /_* <module> *_/
 * /_* </module> *_/
 */
export async function createTypeImports(specifier: string, base = '.') {
	let imports = `// deno-lint-ignore-file no-unused-vars\n// This part is auto generated to allow Deno to resolve the ${specifier}-modules`;
	const originalPath = path.resolve(base);
	let index=0;
	for await (const dirEntry of walk(originalPath, { exts: ["ts"]})) {
		const currentPath = `${specifier}/${path.relative(originalPath, dirEntry.path)}`;
		imports += `\nimport type * as _${specifier}_${index} from "${currentPath}";`;
		index++;
	}
	console.info(`Found ${index} modules`);
	return imports;
}

async function replaceImports() {
	for await (const dirEntry of walk('.', { exts: ["ts"]})) {
		const path = dirEntry.path;
		const content = Deno.readTextFileSync(path);
		if (content.match(regex)) {
			Deno.writeTextFileSync(path, content.replace(regex, `/* <module> */\n${data}\n/* </module> */`));
			console.info(`Replaced module tags in ${path}`);
			return true;
		}
	}
	return false;
}

function runGitHubCommand(...args: string[]) {
	return new Deno.Command('git', { args: args, cwd: "." }).outputSync().success;
}
const branchName = "dependency-bump";

if (!(await replaceImports()))
	throw new Error("Could not find module reference. Skipping");

console.info("Replaced modules");
runGitHubCommand("checkout", "-b", branchName);
runGitHubCommand("add", ".");
runGitHubCommand("commit", "-m", "Updating module imports");
runGitHubCommand("push", "origin", branchName);

const githubAPIUrl = `https://api.github.com/repos/${repository}/pulls`;

const response = await fetch(githubAPIUrl, {
	method: "POST",
	headers: {
		"Content-Type": "application/json",
		"Authorization": `token ${token}`,
	},
	body: JSON.stringify({
		title: "Module bump",
		head: branchName,
		base: "main",
		body: "Auto generated by CI"
	}),
});

const prData = await response.json();
if (!response.ok)
	throw new Error(`Could not create PR ${prData}`);
console.log(`Pull request created: ${prData.html_url}`);